package com.keak.aishou.navigation

interface Router {
    fun goBack()
    fun goToHome()
    fun goToAllResultScreen()
    fun goToQuickTestScreen()
    fun goToPersonalResultScreen()
    fun goToQuizScreen(quizID: String)
    fun goToQuizScreenWithSender(quizID: String, senderId: String)
    fun goToQuizScreenWithInvite(quizID: String, senderId: String, inviteId: String)
    fun goToQuickQuizScreen()
    fun goToDefaultQuizScreen() // Quick start with default test
    fun goToTestResultScreen(testID: String)
    fun goToSplash()
    fun goToReAuth()
    fun goToPaywall()
    fun goToPaywallWithReturn(returnTo: String)
    fun navigateToRoute(route: String)
    fun goToOnBoarding()
    fun goToOnBoardingSecond()
    fun goToOnBoardingThird()
    fun goToOnBoardingFourth()
    fun goToZodiacSelection()
    fun goToMBTIPreference()
    fun goToQuickTest()
    fun goToFriends()
    fun goToNotifications()
    fun goToFriendRequest(senderId: String, senderName: String)
    fun goToInvite(inviteId: String, senderId: String, testId: String, testTitle: String, senderName: String = "Unknown User", senderMbti: String? = null)
    fun goToUserMatch(testID: String)
    fun goToUserMatchWithFriend(testID: String, friendId: String)
    fun goToProfile()
    fun goToThankYou(isFromInvite: Boolean = false)
    fun goToMBTIResult()

}